RazorPagesMVVM/Pages/Tags/Bootstrap.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesMVVM.Pages.Tags
{
    public class BootstrapModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

RazorPagesMVVM/Pages/Tags/CacheTag.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesMVVM.Pages.Tags
{
    public class CacheTagModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

RazorPagesMVVM/Pages/Tags/CustomTag.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesMVVM.Pages.Tags
{
    public class CustomTagModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

RazorPagesMVVM/Pages/Tags/Formulario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorPagesMVVM.Models;
using System.Collections.Generic;

namespace RazorPagesMVVM.Pages.Tags
{
    public class FormularioModel : PageModel
    {
        public Persona Persona { get; set; }
        public List<SelectListItem> PreguntasSeguridad
        {
            get
            {
                var escogido = Persona?.Pregunta;
                var preguntas = ObtenerPreguntasDeSeguridad();
                var opciones = new List<SelectListItem>();
                foreach (var pregunta in preguntas)
                {
                    opciones.Add(new SelectListItem()
                    {
                        Text = pregunta,
                        Value = pregunta,
                        Selected = pregunta == escogido
                    });
                }
                return opciones;
            }
        }

        private List<string> ObtenerPreguntasDeSeguridad()
        {
            return new List<string>() { "Cual es la nacionalidad de su perro?", "Pepsi o Coca Cola?", "Nombre de una persona que usted no conoce?"};
        }

        public void OnGet()
        {

        }

        [ValidateAntiForgeryToken]
        public void OnPostConToken()
        {
            if (ModelState.IsValid)
            {
                
            }
        }
    }
}

RazorPagesMVVM/Pages/Tags/Bootstrap.cshtml
@page
@model RazorPagesMVVM.Pages.Tags.BootstrapModel
@{
    ViewData["Title"] = "Bootstrap";
}

<h1>Bootstrap</h1>

<button type="button"
        class="btn btn-primary btn-lg"
        bs-toggle-modal="simpleModal">
    Launch modal
</button>
<modal id="simpleModal"
       title="Modal Title">
    <modal-body>
        <h4>Something happened</h4>
        <p>Something happened</p>
    </modal-body>
</modal>

RazorPagesMVVM/Pages/Tags/CacheTag.cshtml
@page
@model RazorPagesMVVM.Pages.Tags.CacheTagModel
@{
    ViewData["Title"] = "CacheTag";
}

<h1>CacheTag</h1>
<span>Sin cache: @DateTime.Now</span>
<br />
<cache expires-after="@TimeSpan.FromSeconds(5)">
    Con cache: @DateTime.Now
</cache>

RazorPagesMVVM/Pages/Tags/CustomTag.cshtml
@page
@model RazorPagesMVVM.Pages.Tags.CustomTagModel
@{
    ViewData["Title"] = "CustomTag";
    var aprobado = true;
}

<h1>Personalizado</h1>

<div Condition="aprobado">Usted ha sido aprobado</div>
<div Condition="!aprobado">Usted ha sido rechazado</div>

RazorPagesMVVM/Pages/Tags/Formulario.cshtml
@page
@model RazorPagesMVVM.Pages.Tags.FormularioModel
@{
    ViewData["Title"] = "Formulario";
}

<h1>Formulario</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="Persona.Nombre"></label>
        <input asp-for="Persona.Nombre" />
        <span asp-validation-for="Persona.Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Persona.Edad"></label>
        <input asp-for="Persona.Edad" />
        <span asp-validation-for="Persona.Edad" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Persona.Pais"></label>
        <select asp-for="Persona.Pais" asp-items="Html.GetEnumSelectList<Models.Pais>()"></select>
        <span asp-validation-for="Persona.Pais" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Persona.Pregunta"></label>
        <select asp-for="Persona.Pregunta" asp-items="Model.PreguntasSeguridad">
            <option value="">Escoger</option>
        </select>
        <span asp-validation-for="Persona.Pregunta" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Persona.Descripcion"></label>
        <textarea asp-for="Persona.Descripcion"></textarea>
        <span asp-validation-for="Persona.Descripcion" class="text-danger"></span>
    </div>
    <button type="submit" asp-page-handler="ConToken">Enviar</button>
</form>