RazorPagesMVVM/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorPagesMVVM.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesMVVM/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesMVVM.Models;

namespace RazorPagesMVVM.Pages
{
    // IndexModel es un viewModel y le podemos agregar las propiedades que consideremos necesarias
    // por eso agregamos Persona como una propiedad
    public class IndexModel : PageModel
    {
        [BindProperty]
        public Persona Persona { get; set; }
        [BindProperty]
        public Ciudad Ciudad { get; set; }
        [TempData]
        public string Nombre { get; set; }

        public IActionResult OnPost(string txtSimple)
        {
            Nombre = txtSimple;
            return RedirectToPage("Privacy");
        }

        public void OnPostPersona()
        {
        }

        public void OnPostPersonaCiudad()
        {
        }
    }
}

RazorPagesMVVM/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesMVVM.Pages
{
    public class PrivacyModel : PageModel
    {
        [TempData]
        public string Nombre { get; set; }

        public string Message { get; set; }

        public void OnGet(int id, int pg)
        {
            Message = $"Valores: id:{id} pg:{pg}";
        }
    }
}

RazorPagesMVVM/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form method="post">
    <h1>Formulario simple</h1>
    <input type="text" name="txtSimple" value="" />
    <button type="submit">Enviar</button>
</form>

<form method="post">
    <h1>Persona</h1>
    <input asp-for="@Model.Persona.Id" placeholder= "Id" />
    <input asp-for="@Model.Persona.Nombre" placeholder= "Nombre" />
    <button type="submit" asp-page-handler="Persona">Enviar</button>
</form>

<form method="post">
    <h1>Persona</h1>
    <input asp-for="@Model.Persona.Id" placeholder="Id" />
    <input asp-for="@Model.Persona.Nombre" placeholder="Nombre" />

    <h1>Ciudad</h1>
    <input asp-for="@Model.Ciudad.Id" placeholder="Id" />
    <input asp-for="@Model.Ciudad.Nombre" placeholder="Nombre" />
    <input asp-for="@Model.Ciudad.Pais" placeholder="Pais" />

    <button type="submit" asp-page-handler="PersonaCiudad">Enviar</button>
</form>